// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: proto/logging.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_NONE        LogLevel = 0
	LogLevel_DEBUG       LogLevel = 1
	LogLevel_INFORMATION LogLevel = 2
	LogLevel_WARNING     LogLevel = 3
	LogLevel_ERROR       LogLevel = 4
	LogLevel_CRITICAL    LogLevel = 5
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "NONE",
		1: "DEBUG",
		2: "INFORMATION",
		3: "WARNING",
		4: "ERROR",
		5: "CRITICAL",
	}
	LogLevel_value = map[string]int32{
		"NONE":        0,
		"DEBUG":       1,
		"INFORMATION": 2,
		"WARNING":     3,
		"ERROR":       4,
		"CRITICAL":    5,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logging_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_proto_logging_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_proto_logging_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PreCategory   string                 `protobuf:"bytes,2,opt,name=pre_category,json=preCategory,proto3" json:"pre_category,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	SubCategory   string                 `protobuf:"bytes,4,opt,name=sub_category,json=subCategory,proto3" json:"sub_category,omitempty"`
	LogLevel      LogLevel               `protobuf:"varint,5,opt,name=log_level,json=logLevel,proto3,enum=logging.LogLevel" json:"log_level,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_logging_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_logging_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogEntry) GetPreCategory() string {
	if x != nil {
		return x.PreCategory
	}
	return ""
}

func (x *LogEntry) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *LogEntry) GetSubCategory() string {
	if x != nil {
		return x.SubCategory
	}
	return ""
}

func (x *LogEntry) GetLogLevel() LogLevel {
	if x != nil {
		return x.LogLevel
	}
	return LogLevel_NONE
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LogEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_proto_logging_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_proto_logging_proto_rawDescGZIP(), []int{1}
}

func (x *LogBatch) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_logging_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logging_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_logging_proto_rawDescGZIP(), []int{2}
}

var File_proto_logging_proto protoreflect.FileDescriptor

const file_proto_logging_proto_rawDesc = "" +
	"\n" +
	"\x13proto/logging.proto\x12\alogging\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\bLogEntry\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fpre_category\x18\x02 \x01(\tR\vpreCategory\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12!\n" +
	"\fsub_category\x18\x04 \x01(\tR\vsubCategory\x12.\n" +
	"\tlog_level\x18\x05 \x01(\x0e2\x11.logging.LogLevelR\blogLevel\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"7\n" +
	"\bLogBatch\x12+\n" +
	"\aentries\x18\x01 \x03(\v2\x11.logging.LogEntryR\aentries\"\x0f\n" +
	"\rWriteResponse*V\n" +
	"\bLogLevel\x12\b\n" +
	"\x04NONE\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\x0f\n" +
	"\vINFORMATION\x10\x02\x12\v\n" +
	"\aWARNING\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04\x12\f\n" +
	"\bCRITICAL\x10\x052u\n" +
	"\x06Logger\x122\n" +
	"\x05Write\x12\x11.logging.LogEntry\x1a\x16.logging.WriteResponse\x127\n" +
	"\n" +
	"WriteBatch\x12\x11.logging.LogBatch\x1a\x16.logging.WriteResponseB0Z.github.com/sudzekai-web-os/logging/proto;protob\x06proto3"

var (
	file_proto_logging_proto_rawDescOnce sync.Once
	file_proto_logging_proto_rawDescData []byte
)

func file_proto_logging_proto_rawDescGZIP() []byte {
	file_proto_logging_proto_rawDescOnce.Do(func() {
		file_proto_logging_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logging_proto_rawDesc), len(file_proto_logging_proto_rawDesc)))
	})
	return file_proto_logging_proto_rawDescData
}

var file_proto_logging_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logging_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_logging_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: logging.LogLevel
	(*LogEntry)(nil),              // 1: logging.LogEntry
	(*LogBatch)(nil),              // 2: logging.LogBatch
	(*WriteResponse)(nil),         // 3: logging.WriteResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_proto_logging_proto_depIdxs = []int32{
	4, // 0: logging.LogEntry.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: logging.LogEntry.log_level:type_name -> logging.LogLevel
	1, // 2: logging.LogBatch.entries:type_name -> logging.LogEntry
	1, // 3: logging.Logger.Write:input_type -> logging.LogEntry
	2, // 4: logging.Logger.WriteBatch:input_type -> logging.LogBatch
	3, // 5: logging.Logger.Write:output_type -> logging.WriteResponse
	3, // 6: logging.Logger.WriteBatch:output_type -> logging.WriteResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_logging_proto_init() }
func file_proto_logging_proto_init() {
	if File_proto_logging_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logging_proto_rawDesc), len(file_proto_logging_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logging_proto_goTypes,
		DependencyIndexes: file_proto_logging_proto_depIdxs,
		EnumInfos:         file_proto_logging_proto_enumTypes,
		MessageInfos:      file_proto_logging_proto_msgTypes,
	}.Build()
	File_proto_logging_proto = out.File
	file_proto_logging_proto_goTypes = nil
	file_proto_logging_proto_depIdxs = nil
}
